/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SimCardService } from "../simCard.service";
import { SimCardCreateInput } from "./SimCardCreateInput";
import { SimCard } from "./SimCard";
import { SimCardFindManyArgs } from "./SimCardFindManyArgs";
import { SimCardWhereUniqueInput } from "./SimCardWhereUniqueInput";
import { SimCardUpdateInput } from "./SimCardUpdateInput";
import { RentalFindManyArgs } from "../../rental/base/RentalFindManyArgs";
import { Rental } from "../../rental/base/Rental";
import { RentalWhereUniqueInput } from "../../rental/base/RentalWhereUniqueInput";

export class SimCardControllerBase {
  constructor(protected readonly service: SimCardService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SimCard })
  async createSimCard(
    @common.Body() data: SimCardCreateInput
  ): Promise<SimCard> {
    return await this.service.createSimCard({
      data: {
        ...data,

        modem: data.modem
          ? {
              connect: data.modem,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        phoneNumber: true,

        modem: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SimCard] })
  @ApiNestedQuery(SimCardFindManyArgs)
  async simCards(@common.Req() request: Request): Promise<SimCard[]> {
    const args = plainToClass(SimCardFindManyArgs, request.query);
    return this.service.simCards({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        phoneNumber: true,

        modem: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SimCard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async simCard(
    @common.Param() params: SimCardWhereUniqueInput
  ): Promise<SimCard | null> {
    const result = await this.service.simCard({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        phoneNumber: true,

        modem: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SimCard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSimCard(
    @common.Param() params: SimCardWhereUniqueInput,
    @common.Body() data: SimCardUpdateInput
  ): Promise<SimCard | null> {
    try {
      return await this.service.updateSimCard({
        where: params,
        data: {
          ...data,

          modem: data.modem
            ? {
                connect: data.modem,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          phoneNumber: true,

          modem: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SimCard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSimCard(
    @common.Param() params: SimCardWhereUniqueInput
  ): Promise<SimCard | null> {
    try {
      return await this.service.deleteSimCard({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          phoneNumber: true,

          modem: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/rentals")
  @ApiNestedQuery(RentalFindManyArgs)
  async findRentals(
    @common.Req() request: Request,
    @common.Param() params: SimCardWhereUniqueInput
  ): Promise<Rental[]> {
    const query = plainToClass(RentalFindManyArgs, request.query);
    const results = await this.service.findRentals(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        startDate: true,
        endDate: true,

        user: {
          select: {
            id: true,
          },
        },

        simCard: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/rentals")
  async connectRentals(
    @common.Param() params: SimCardWhereUniqueInput,
    @common.Body() body: RentalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rentals: {
        connect: body,
      },
    };
    await this.service.updateSimCard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/rentals")
  async updateRentals(
    @common.Param() params: SimCardWhereUniqueInput,
    @common.Body() body: RentalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rentals: {
        set: body,
      },
    };
    await this.service.updateSimCard({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/rentals")
  async disconnectRentals(
    @common.Param() params: SimCardWhereUniqueInput,
    @common.Body() body: RentalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rentals: {
        disconnect: body,
      },
    };
    await this.service.updateSimCard({
      where: params,
      data,
      select: { id: true },
    });
  }
}
